version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: linkedin_sequencer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/linkedin_sequencer
      - REDIS_URL=redis://redis:6379
  
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
  
volumes:
  postgres_data:
